import { NFTItem } from './store';

export const realNFTs: NFTItem[] = [
  {
    id: 'dolphin-1',
    title: 'Dolphin Paradise',
    creator: 'OceanExplorer',
    creatorAvatar: '/placeholder-user.jpg',
    image: '/Dolphin-1.jpg',
    price: 2.5,
    floorPrice: 2.0,
    rarity: 'legendary' as const,
    likes: 342,
    liked: false,
    collection: 'Ocean Dreams',
    owner: '0x1234...5678',
    createdAt: '2 days ago',
    description: 'A majestic dolphin swimming in crystal clear waters',
    traits: [
      { name: 'Theme', value: 'Ocean' },
      { name: 'Color', value: 'Blue' },
      { name: 'Rarity', value: 'Legendary' }
    ],
    priceHistory: [{ date: '2024-03-15', price: 2.5 }],
    ownershipHistory: [{ address: '0x1234...5678', date: '2024-03-15' }]
  },
  {
    id: 'dolphin-2',
    title: 'Ocean Guardian',
    creator: 'SeaWorld',
    creatorAvatar: '/placeholder-user.jpg',
    image: '/Dolphin-2.jpg',
    price: 1.8,
    floorPrice: 1.5,
    rarity: 'epic' as const,
    likes: 256,
    liked: false,
    collection: 'Marine Life',
    owner: '0xabcd...ef01',
    createdAt: '3 days ago',
    description: 'Guardian of the deep blue sea',
    traits: [
      { name: 'Theme', value: 'Ocean' },
      { name: 'Color', value: 'Deep Blue' },
      { name: 'Rarity', value: 'Epic' }
    ],
    priceHistory: [{ date: '2024-03-14', price: 1.8 }],
    ownershipHistory: [{ address: '0xabcd...ef01', date: '2024-03-14' }]
  },
  {
    id: 'dolphin-3',
    title: 'Aqua Dream',
    creator: 'DolphinLover',
    creatorAvatar: '/placeholder-user.jpg',
    image: '/Dolphin-3.jpg',
    price: 3.2,
    floorPrice: 2.8,
    rarity: 'legendary' as const,
    likes: 445,
    liked: false,
    collection: 'Ocean Dreams',
    owner: '0x2345...6789',
    createdAt: '1 day ago',
    description: 'Dreamy underwater scene with playful dolphins',
    traits: [
      { name: 'Theme', value: 'Ocean' },
      { name: 'Color', value: 'Aqua' },
      { name: 'Rarity', value: 'Legendary' }
    ],
    priceHistory: [{ date: '2024-03-16', price: 3.2 }],
    ownershipHistory: [{ address: '0x2345...6789', date: '2024-03-16' }]
  },
  {
    id: 'dolphin-4',
    title: 'Marine Symphony',
    creator: 'WaveRider',
    creatorAvatar: '/placeholder-user.jpg',
    image: '/Dolphin-4.jpg',
    price: 1.5,
    floorPrice: 1.2,
    rarity: 'rare' as const,
    likes: 189,
    liked: false,
    collection: 'Marine Life',
    owner: '0x3456...7890',
    createdAt: '4 days ago',
    description: 'Symphony of ocean waves and dolphin songs',
    traits: [
      { name: 'Theme', value: 'Ocean' },
      { name: 'Color', value: 'Ocean Blue' },
      { name: 'Rarity', value: 'Rare' }
    ],
    priceHistory: [{ date: '2024-03-13', price: 1.5 }],
    ownershipHistory: [{ address: '0x3456...7890', date: '2024-03-13' }]
  },
  {
    id: 'dolphin-5',
    title: 'Crystal Waters',
    creator: 'DeepSea',
    creatorAvatar: '/placeholder-user.jpg',
    image: '/Dolphin-5.jpg',
    price: 2.8,
    floorPrice: 2.5,
    rarity: 'epic' as const,
    likes: 378,
    liked: false,
    collection: 'Ocean Dreams',
    owner: '0x4567...8901',
    createdAt: '5 days ago',
    description: 'Crystal clear waters with dancing dolphins',
    traits: [
      { name: 'Theme', value: 'Ocean' },
      { name: 'Color', value: 'Crystal' },
      { name: 'Rarity', value: 'Epic' }
    ],
    priceHistory: [{ date: '2024-03-12', price: 2.8 }],
    ownershipHistory: [{ address: '0x4567...8901', date: '2024-03-12' }]
  },
  {
    id: 'dolphin-7',
    title: 'Ocean Explorer',
    creator: 'SeaVoyager',
    creatorAvatar: '/placeholder-user.jpg',
    image: '/Dolphin-7.jpg',
    price: 1.2,
    floorPrice: 1.0,
    rarity: 'common' as const,
    likes: 98,
    liked: false,
    collection: 'Marine Life',
    owner: '0x5678...9012',
    createdAt: '1 week ago',
    description: 'Explorer dolphin discovering new territories',
    traits: [
      { name: 'Theme', value: 'Ocean' },
      { name: 'Color', value: 'Sea Green' },
      { name: 'Rarity', value: 'Common' }
    ],
    priceHistory: [{ date: '2024-03-10', price: 1.2 }],
    ownershipHistory: [{ address: '0x5678...9012', date: '2024-03-10' }]
  },
  {
    id: 'dolphin-9',
    title: 'Wave Dancer',
    creator: 'OceanDance',
    creatorAvatar: '/placeholder-user.jpg',
    image: '/Dolphin-9.jpg',
    price: 2.1,
    floorPrice: 1.9,
    rarity: 'rare' as const,
    likes: 267,
    liked: false,
    collection: 'Ocean Dreams',
    owner: '0x6789...0123',
    createdAt: '6 days ago',
    description: 'Dolphin dancing through ocean waves',
    traits: [
      { name: 'Theme', value: 'Ocean' },
      { name: 'Color', value: 'Wave Blue' },
      { name: 'Rarity', value: 'Rare' }
    ],
    priceHistory: [{ date: '2024-03-11', price: 2.1 }],
    ownershipHistory: [{ address: '0x6789...0123', date: '2024-03-11' }]
  },
  {
    id: 'dolphin-10',
    title: 'Deep Blue',
    creator: 'AquaMaster',
    creatorAvatar: '/placeholder-user.jpg',
    image: '/Dolphin-10.jpg',
    price: 3.5,
    floorPrice: 3.0,
    rarity: 'legendary' as const,
    likes: 512,
    liked: false,
    collection: 'Marine Life',
    owner: '0x7890...1234',
    createdAt: '2 weeks ago',
    description: 'Deep blue ocean with mysterious dolphin',
    traits: [
      { name: 'Theme', value: 'Ocean' },
      { name: 'Color', value: 'Deep Blue' },
      { name: 'Rarity', value: 'Legendary' }
    ],
    priceHistory: [{ date: '2024-03-08', price: 3.5 }],
    ownershipHistory: [{ address: '0x7890...1234', date: '2024-03-08' }]
  },
  {
    id: 'dolphin-11',
    title: 'Ocean Pearl',
    creator: 'PearlDiver',
    creatorAvatar: '/placeholder-user.jpg',
    image: '/Dolphin-11.jpg',
    price: 1.8,
    floorPrice: 1.5,
    rarity: 'rare' as const,
    likes: 234,
    liked: false,
    collection: 'Ocean Dreams',
    owner: '0x8901...2345',
    createdAt: '3 weeks ago',
    description: 'Precious ocean pearl with dolphin guardian',
    traits: [
      { name: 'Theme', value: 'Ocean' },
      { name: 'Color', value: 'Pearl White' },
      { name: 'Rarity', value: 'Rare' }
    ],
    priceHistory: [{ date: '2024-03-07', price: 1.8 }],
    ownershipHistory: [{ address: '0x8901...2345', date: '2024-03-07' }]
  },
  {
    id: 'dolphin-12',
    title: 'Sea Harmony',
    creator: 'HarmonySea',
    creatorAvatar: '/placeholder-user.jpg',
    image: '/Dolphin-12.jpg',
    price: 2.2,
    floorPrice: 2.0,
    rarity: 'epic' as const,
    likes: 389,
    liked: false,
    collection: 'Marine Life',
    owner: '0x9012...3456',
    createdAt: '1 month ago',
    description: 'Perfect harmony between dolphins and sea',
    traits: [
      { name: 'Theme', value: 'Ocean' },
      { name: 'Color', value: 'Sea Green' },
      { name: 'Rarity', value: 'Epic' }
    ],
    priceHistory: [{ date: '2024-03-06', price: 2.2 }],
    ownershipHistory: [{ address: '0x9012...3456', date: '2024-03-06' }]
  }
];
